name: ci-v133-maintenance

on:
  push:
    branches: ['topic-v133-maintenance']
jobs:
  build:
    name: Java ${{ matrix.java }}/${{ matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: ['8']
    steps:
    - name: Checkout source
      uses: actions/checkout@v1
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Ant
      run: ant clean clean-packages release
